### ISSUE TITLE
spread is only in portfolio

### ISSUE THREAD

**Issue by no-matter-0** [vanduc1102/etoro-helper#4] opened 2020-03-12 16:20 UTC
Thanks for this extension but the spread  only appears in the portfolio. We don't see it where it's most needed, on the watchlist.

**Comment by vanduc1102** [comment] 2020-03-13 04:39
thanks @no-matter-0 
i will check and update to you.

**Comment by no-matter-0** [comment] 2020-03-13 14:07
with "blood in the street" it would be good to have it working now :-)

**Comment by vanduc1102** [comment] 2020-04-09 09:40
hi @no-matter-0 ,
I hope it is not too late now, 
the issue is fixed in latest version.

**Closed as completed by vanduc1102** 2020-04-09 09:40 UTC
